### ISSUE TITLE
Unmatched NVMe-CLI command running in CSI Node Driver

### ISSUE THREAD

**Issue by dong-liuliu** [eosphoros-ai/liteio#5]
As described in `quick-start.md` and `800-csi-node.yaml`, currently the `nvme` cmd used in csi-node-driver is installed inside the compute server node, and availabe to csi-node-driver through mounted volume `/home/admin/nvmeof/bin`.

This might not be a good choice. Since it implicitly add limitation that the host server and container pod keep consistency with each other on shared libraries, like glibc. If not, then when csi-node-driver calls the `nvme` cmd shared from host server, it fails on error like "not found specific GLIBC version".
```
$/home/admin/nvmeof/bin/nvme
/home/admin/nvmeof/bin/nvme: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /home/admin/nvmeof/bin/nvme)
/home/admin/nvmeof/bin/nvme: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /home/admin/nvmeof/bin/nvme)
```

How about installing nvme-cli directly inside the image csi node driver is using?

**Comment by silentred** [comment]
@dong-liuliu Thanks, it is a good advice! 
For now, the quick-start deployment is tested on `CentOS7.9`, and CSI's base image is `debian:bullseye-slim`. I will install nvme command to CSI image later and update the document.

**Comment by dong-liuliu** [comment]
Thank you, @silentred
